language: ruby

rvm: 2.4.2

cache: bundler

env:
- GH_REPO_URL="git@github.com:${TRAVIS_REPO_SLUG}.git" GIT_DEPLOY_USERNAME="Travis CI" GIT_DEPLOY_EMAIL=""

script: bundle exec middleman build

before_deploy:
- openssl aes-256-cbc -K $encrypted_bf0a6ebd7ff4_key -iv $encrypted_bf0a6ebd7ff4_iv -in zenodo_docs_api_rsa.enc -out zenodo_docs_api_rsa -d
- chmod 600 ./zenodo_docs_api_rsa
- eval $(ssh-agent -s)
- ssh-add ./zenodo_docs_api_rsa
- git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}.git

deploy:
  skip_cleanup: true
  provider: script
  script: bundle install && ./deploy.sh
  on:
    branch: master
